import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import { Download, Copy, Sparkles, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLocalState, KEYS, writeLS } from "@/lib/storage";
import type {
  ActivityItem,
  Condition,
  LogEntry,
  LogMetric,
  Medication,
  MedicalSummary,
  Profile,
} from "@/lib/types";
import { fmtDate, todayISO } from "@/lib/format";
import { differenceInDays, parseISO } from "date-fns";
import { summaryApi } from "@/lib/baymax-api";
import { APP_NAME } from "@/lib/brand";

export const Route = createFileRoute("/visit-summary")({
  head: () => ({
    meta: [
      { title: `Doctor Visit Summary — ${APP_NAME}` },
      { name: "description", content: "A printable summary for your next appointment." },
    ],
  }),
  component: VisitSummary,
});

function VisitSummary() {
  const [profile] = useLocalState<Profile | null>(KEYS.profile, null);
  const [conditions] = useLocalState<Condition[]>(KEYS.conditions, []);
  const [meds] = useLocalState<Medication[]>(KEYS.meds, []);
  const [metrics] = useLocalState<LogMetric[]>(KEYS.metrics, []);
  const [entries] = useLocalState<LogEntry[]>(KEYS.entries, []);
  const [activity] = useLocalState<ActivityItem[]>(KEYS.activity, []);
  const [summary, setSummary] = useLocalState<MedicalSummary | null>(KEYS.summary, null);
  const [generating, setGenerating] = useState(false);
  const [backendSummary, setBackendSummary] = useState<string | null>(null);
  const [summaryUpdatedAt, setSummaryUpdatedAt] = useState<string | null>(null);

  // Try to pull the latest backend summary on mount
  useEffect(() => {
    summaryApi.latest()
      .then((res: any) => {
        setBackendSummary(res.summary);
        if (res.updated_at) setSummaryUpdatedAt(res.updated_at);
      })
      .catch(() => {}); // silent — will use local summary
  }, []);

  const trends = useMemo(() => metrics.filter((m) => m.unit !== "text").map((m) => {
    const vals = entries.filter((e) => e.metricId === m.id).map((e) => Number(e.value)).filter((n) => !Number.isNaN(n));
    if (vals.length === 0) return { name: m.name, unit: m.unit, avg: null as number | null, n: 0 };
    return {
      name: m.name,
      unit: m.unit,
      avg: Math.round((vals.reduce((a, b) => a + b, 0) / vals.length) * 10) / 10,
      n: vals.length,
    };
  }), [metrics, entries]);

  const gaps = useMemo(() => {
    const today = parseISO(todayISO());
    return metrics.filter((m) => {
      const last = entries.filter((e) => e.metricId === m.id).sort((a, b) => b.date.localeCompare(a.date))[0];
      if (!last) return true;
      return differenceInDays(today, parseISO(last.date)) > 7;
    });
  }, [metrics, entries]);

  const anomalies = activity.filter((a) => a.severity !== "info");

  const buildText = () => {
    const lines = [
      `# ${APP_NAME} — Doctor Visit Summary`,
      `Generated: ${fmtDate(todayISO())}`,
      ``,
      `## Patient`,
      `- Name: ${profile?.name || "—"}`,
      `- Age: ${profile?.age || "—"}`,
      `- Gender: ${profile?.gender || "—"}`,
      `- City: ${profile?.city || "—"}`,
      ``,
      `## Conditions`,
      ...(conditions.length ? conditions.map((c) => `- ${c.label}`) : ["- None recorded"]),
      ``,
      `## Medications`,
      ...(meds.length ? meds.map((m) => `- ${m.name} ${m.dosage} @ ${m.time}`) : ["- None recorded"]),
      ``,
      `## Recent trends`,
      ...trends.map((t) => t.avg === null ? `- ${t.name}: no data` : `- ${t.name}: avg ${t.avg} ${t.unit} (n=${t.n})`),
      ``,
      `## Anomalies`,
      ...(anomalies.length ? anomalies.map((a) => `- [${a.severity}] ${a.title} — ${a.body}`) : ["- None"]),
      ``,
      `## Data gaps (no entry in 7+ days)`,
      ...(gaps.length ? gaps.map((g) => `- ${g.name}`) : ["- None"]),
      ``,
      summary ? `## AI summary\n\n${summary.content}` : "",
    ];
    return lines.join("\n");
  };

  // The display summary prefers: backend AI summary > locally stored > generated from local data
  const displaySummary = backendSummary ?? summary?.content ?? null;

  const generateBackendSummary = async () => {
    setGenerating(true);
    try {
      const res: any = await summaryApi.generate();
      setBackendSummary(res.summary);
      if (res.generated_at) setSummaryUpdatedAt(res.generated_at);
      // Also save locally as fallback
      setSummary({ generatedAt: Date.now(), content: res.summary });
      toast.success("Doctor summary generated by Baymax");
    } catch {
      toast.error("Could not generate summary — ensure the backend is running.");
    } finally {
      setGenerating(false);
    }
  };

  const copy = async () => {
    await navigator.clipboard.writeText(buildText());
    toast.success("Summary copied to clipboard");
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between no-print">
        <h1 className="text-xl font-semibold">Doctor Visit Summary</h1>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={generateBackendSummary}
            disabled={generating}
          >
            {generating
              ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</>
              : <><Sparkles className="h-4 w-4" /> AI Generate</>}
          </Button>
          <Button variant="secondary" onClick={copy}><Copy className="h-4 w-4" /> Copy</Button>
          <Button onClick={() => window.print()}><Download className="h-4 w-4" /> Download PDF</Button>
        </div>
      </div>

      {/* ── AI Clinical Summary (primary section) ─────────────────────────── */}
      {displaySummary ? (
        <div className="rounded-2xl border border-primary/20 bg-gradient-to-b from-primary/5 to-transparent overflow-hidden">
          {/* Header */}
          <div className="flex items-center justify-between px-5 py-3 border-b border-primary/10 bg-primary/5">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              <span className="text-sm font-semibold text-primary">BayMax Clinical Summary</span>
            </div>
            {summaryUpdatedAt && (
              <span className="text-xs text-muted-foreground">
                Generated {new Date(summaryUpdatedAt).toLocaleString()}
              </span>
            )}
          </div>
          {/* Body */}
          <div className="px-6 py-5">
            <div className="prose prose-sm max-w-none
              prose-headings:font-semibold prose-headings:text-foreground
              prose-h2:text-base prose-h2:mt-6 prose-h2:mb-2 prose-h2:border-b prose-h2:pb-1 prose-h2:border-border
              prose-h3:text-sm prose-h3:mt-4 prose-h3:mb-1
              prose-strong:text-foreground
              prose-p:my-1 prose-li:my-0.5
              prose-ul:my-1 prose-ol:my-1">
              <ReactMarkdown>{displaySummary}</ReactMarkdown>
            </div>
          </div>
        </div>
      ) : (
        <div className="rounded-2xl border border-dashed border-muted-foreground/30 bg-muted/20 px-6 py-10 text-center">
          <Sparkles className="h-8 w-8 text-muted-foreground/50 mx-auto mb-3" />
          <p className="text-sm font-medium text-muted-foreground">No AI summary yet</p>
          <p className="text-xs text-muted-foreground/70 mt-1">Click <strong>AI Generate</strong> above to create a clinical summary that includes your chat history.</p>
        </div>
      )}

      <Card>
        <CardContent className="p-6 prose prose-sm max-w-none">
          <ReactMarkdown>{buildText()}</ReactMarkdown>
        </CardContent>
      </Card>
    </div>
  );
}
