/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitSummaryRouteImport } from './routes/visit-summary'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PeriodRouteImport } from './routes/period'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'

const VisitSummaryRoute = VisitSummaryRouteImport.update({
  id: '/visit-summary',
  path: '/visit-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodRoute = PeriodRouteImport.update({
  id: '/period',
  path: '/period',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/period': typeof PeriodRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trends': typeof TrendsRoute
  '/visit-summary': typeof VisitSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/period': typeof PeriodRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trends': typeof TrendsRoute
  '/visit-summary': typeof VisitSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/period': typeof PeriodRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trends': typeof TrendsRoute
  '/visit-summary': typeof VisitSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/onboarding'
    | '/period'
    | '/reports'
    | '/settings'
    | '/trends'
    | '/visit-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/onboarding'
    | '/period'
    | '/reports'
    | '/settings'
    | '/trends'
    | '/visit-summary'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/onboarding'
    | '/period'
    | '/reports'
    | '/settings'
    | '/trends'
    | '/visit-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  OnboardingRoute: typeof OnboardingRoute
  PeriodRoute: typeof PeriodRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TrendsRoute: typeof TrendsRoute
  VisitSummaryRoute: typeof VisitSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit-summary': {
      id: '/visit-summary'
      path: '/visit-summary'
      fullPath: '/visit-summary'
      preLoaderRoute: typeof VisitSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/period': {
      id: '/period'
      path: '/period'
      fullPath: '/period'
      preLoaderRoute: typeof PeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  OnboardingRoute: OnboardingRoute,
  PeriodRoute: PeriodRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TrendsRoute: TrendsRoute,
  VisitSummaryRoute: VisitSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
